SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{60569780DE4EE17A}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{661AA662B845BAFD}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{661AA662897C8B0F}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{661AA662865EE654}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{661AA6629C2A322A}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61DCAE0EFBDD356C}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6484BA2451EAD6CE}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6484EB5D58547F8C}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{652B36FB5E0FCA39}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{652B36FB5FB2E3EF}" {
     m_bEnabled 0
    }
   }
  }
 }
}