SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{605697826E2AC672}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{62E6D156691AB4AF}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{62E6D1566F56AFED}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{62E6D1561C61658D}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65176EB41125592D}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65176EB401FB1C02}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{651CC15B9B152C18}" {
     m_bEnabled 0
    }
   }
  }
 }
}