SCR_Faction : "{E7B7EA4823DD81F0}Configs/Factions/BLUFOR.conf" {
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C68A0EEB3F124F9}" {
   m_aMultiLists {
    SCR_EntityCatalogMultiListEntry "{5C68AD59F0753ABE}" {
     m_aEntities {
      SCR_EntityCatalogInventoryItem "{6590F7D1AAFBF3FE}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogInventoryItem "{65F03A9BEAB6738C}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogInventoryItem "{65F49623ED78AD81}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogInventoryItem "{65F49623E423424B}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogInventoryItem "{65F03A9B0F05A0FB}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogInventoryItem "{65F03A9BE2657D9F}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogInventoryItem "{65F49623E3DC7E4B}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogInventoryItem "{65F49623F405480D}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogInventoryItem "{68A8A78AEF290682}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogInventoryItem "{68AA70AC2E158AF6}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogInventoryItem "{68A8A78A9C77833D}" {
       m_bEnabled 0
      }
     }
    }
    SCR_EntityCatalogMultiListEntry "{5C68AD59AA1A6D59}" {
     m_aEntities {
      SCR_EntityCatalogInventoryItem "{68A8BCD263281A6E}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogInventoryItem "{68A8BCD20D02EE9B}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogInventoryItem "{68A8BCD2B4EB1833}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogInventoryItem "{65F03A9B667E1875}" {
       m_bEnabled 0
      }
     }
    }
   }
  }
 }
}